### ISSUE TITLE
Make release versions compatible with PEP 440

### ISSUE THREAD

**Issue by lorddaedra** [jazzband/django-flatblocks#35] opened 2021-03-08 07:32 UTC
https://www.python.org/dev/peps/pep-0440/

Looks like incompatible version format (like `release/0.9.4`) may add some bugs during installation... #34 #33 

`AssertionError: Can't parse version release/0.9.4`

**Comment by martey** [comment] 2021-03-08 23:11
This is a duplicate of #34.

**Closed by martey** 2021-03-08 23:11 UTC
Labels: duplicate
