### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by lorddaedra** [jazzband/django-flatblocks#34] opened 2021-03-07 19:25 UTC
Several months ago I replaced `django-flatblocks==0.9.4` with `git+https://github.com/jazzband/django-flatblocks` because of some error with (latest stable) Django 3.1. It worked. But now even master is broken...
```
Step #0: + python3 -m pip install --no-cache-dir --upgrade '--upgrade-strategy=eager' git+https://github.com/jazzband/django-flatblocks
Step #0: Collecting git+https://github.com/jazzband/django-flatblocks
Step #0:   Cloning https://github.com/jazzband/django-flatblocks to /tmp/pip-req-build-xh36avr6
Step #0:   Running command git clone -q https://github.com/jazzband/django-flatblocks /tmp/pip-req-build-xh36avr6
Step #0:     ERROR: Command errored out with exit status 1:
Step #0:      command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-xh36avr6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-xh36avr6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ehajisg1
Step #0:          cwd: /tmp/pip-req-build-xh36avr6/
Step #0:     Complete output (33 lines):
Step #0:     /tmp/pip-req-build-xh36avr6/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/version.py:88: UserWarning: tag 'release/0.9.4' no version found
Step #0:       warnings.warn("tag {!r} no version found".format(tag))
Step #0:     Traceback (most recent call last):
Step #0:       File "<string>", line 1, in <module>
Step #0:       File "/tmp/pip-req-build-xh36avr6/setup.py", line 5, in <module>
Step #0:         setup(
Step #0:       File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
Step #0:         return distutils.core.setup(**attrs)
Step #0:       File "/usr/local/lib/python3.8/distutils/core.py", line 108, in setup
Step #0:         _setup_distribution = dist = klass(attrs)
Step #0:       File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 432, in __init__
Step #0:         _Distribution.__init__(self, {
Step #0:       File "/usr/local/lib/python3.8/distutils/dist.py", line 292, in __init__
Step #0:         self.finalize_options()
Step #0:       File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 735, in finalize_options
Step #0:         ep(self)
Step #0:       File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 742, in _finalize_setup_keywords
Step #0:         ep.load()(self, ep.name, value)
Step #0:       File "/tmp/pip-req-build-xh36avr6/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/integration.py", line 26, in version_keyword
Step #0:         dist.metadata.version = _get_version(config)
Step #0:       File "/tmp/pip-req-build-xh36avr6/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/__init__.py", line 173, in _get_version
Step #0:         parsed_version = _do_parse(config)
Step #0:       File "/tmp/pip-req-build-xh36avr6/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/__init__.py", line 127, in _do_parse
Step #0:         version = _version_from_entrypoints(config) or _version_from_entrypoints(
Step #0:       File "/tmp/pip-req-build-xh36avr6/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/__init__.py", line 65, in _version_from_entrypoints
Step #0:         version = _call_entrypoint_fn(root, config, ep.load())
Step #0:       File "/tmp/pip-req-build-xh36avr6/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/__init__.py", line 46, in _call_entrypoint_fn
Step #0:         return fn(root, config=config)
Step #0:       File "/tmp/pip-req-build-xh36avr6/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/git.py", line 144, in parse
Step #0:         return meta(
Step #0:       File "/tmp/pip-req-build-xh36avr6/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/version.py", line 212, in meta
Step #0:         assert parsed_version is not None, "Can't parse version %s" % tag
Step #0:     AssertionError: Can't parse version release/0.9.4
Step #0:     ----------------------------------------
Step #0: WARNING: Discarding git+https://github.com/jazzband/django-flatblocks. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by lorddaedra** [comment] 2021-03-08 07:03
This works for me:
`python3 -m pip install --no-cache-dir --upgrade --upgrade-strategy='eager' 'git+git://github.com/jazzband/django-flatblocks.git@41a037959f05ad666ee9a1645db1907c81e4bd78'`
But it mean I can't receive updates now...

**Comment by lorddaedra** [comment] 2021-03-08 07:06
This bug is somehow relates with https://github.com/jazzband/django-flatblocks/pull/32

**Comment by lorddaedra** [comment] 2021-03-08 07:59
It looks as duplicate of #33 

I tried to fix it with the same command provided by @digicase but got the same bug.
```
Step #0: + python3 -m pip install -e 'git+https://github.com/jazzband/django-flatblocks.git@master#egg=django-flatblocks'
Step #0: Obtaining django-flatblocks from git+https://github.com/jazzband/django-flatblocks.git@master#egg=django-flatblocks
Step #0:   Cloning https://github.com/jazzband/django-flatblocks.git (to revision master) to /src/django-flatblocks
Step #0:   Running command git clone -q https://github.com/jazzband/django-flatblocks.git /src/django-flatblocks
Step #0:     ERROR: Command errored out with exit status 1:
Step #0:      command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/src/django-flatblocks/setup.py'"'"'; __file__='"'"'/src/django-flatblocks/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-544e47wh
Step #0:          cwd: /src/django-flatblocks/
Step #0:     Complete output (33 lines):
Step #0:     /src/django-flatblocks/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/version.py:88: UserWarning: tag 'release/0.9.4' no version found
Step #0:       warnings.warn("tag {!r} no version found".format(tag))
Step #0:     Traceback (most recent call last):
Step #0:       File "<string>", line 1, in <module>
Step #0:       File "/src/django-flatblocks/setup.py", line 5, in <module>
Step #0:         setup(
Step #0:       File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
Step #0:         return distutils.core.setup(**attrs)
Step #0:       File "/usr/local/lib/python3.8/distutils/core.py", line 108, in setup
Step #0:         _setup_distribution = dist = klass(attrs)
Step #0:       File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 432, in __init__
Step #0:         _Distribution.__init__(self, {
Step #0:       File "/usr/local/lib/python3.8/distutils/dist.py", line 292, in __init__
Step #0:         self.finalize_options()
Step #0:       File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 735, in finalize_options
Step #0:         ep(self)
Step #0:       File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 742, in _finalize_setup_keywords
Step #0:         ep.load()(self, ep.name, value)
Step #0:       File "/src/django-flatblocks/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/integration.py", line 26, in version_keyword
Step #0:         dist.metadata.version = _get_version(config)
Step #0:       File "/src/django-flatblocks/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/__init__.py", line 173, in _get_version
Step #0:         parsed_version = _do_parse(config)
Step #0:       File "/src/django-flatblocks/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/__init__.py", line 127, in _do_parse
Step #0:         version = _version_from_entrypoints(config) or _version_from_entrypoints(
Step #0:       File "/src/django-flatblocks/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/__init__.py", line 65, in _version_from_entrypoints
Step #0:         version = _call_entrypoint_fn(root, config, ep.load())
Step #0:       File "/src/django-flatblocks/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/__init__.py", line 46, in _call_entrypoint_fn
Step #0:         return fn(root, config=config)
Step #0:       File "/src/django-flatblocks/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/git.py", line 144, in parse
Step #0:         return meta(
Step #0:       File "/src/django-flatblocks/.eggs/setuptools_scm-5.0.2-py3.8.egg/setuptools_scm/version.py", line 212, in meta
Step #0:         assert parsed_version is not None, "Can't parse version %s" % tag
Step #0:     AssertionError: Can't parse version release/0.9.4
Step #0:     ----------------------------------------
Step #0: WARNING: Discarding git+https://github.com/jazzband/django-flatblocks.git@master#egg=django-flatblocks. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Step #0: ERROR: Could not find a version that satisfies the requirement django-flatblocks (unavailable)
Step #0: ERROR: No matching distribution found for django-flatblocks (unavailable)
Step #0: The command '/bin/sh -c set -ex     && mkdir -p /usr/src/app     && apk upgrade --no-cache     && apk add --upgrade --no-cache --virtual .build-deps         'build-base'         'freetype-dev'         'jpeg-dev'         'git'         'libffi-dev'         'libwebp-dev'         'libxml2-dev'         'libxslt-dev'         'libuv-dev'         'linux-headers'         'openssl-dev'         'pcre-dev'         'postgresql-dev'         'tiff-dev'         'wget'         'zlib-dev'     && apk add --upgrade --no-cache         'bash'         'ca-certificates'         'freetype'         'jpeg'         'libffi'         'libwebp'         'libxml2'         'libxslt'         'libuv'         'openssl'         'pcre'         'postgresql'         'tiff'         'zlib'     && python3 -m pip install --no-cache-dir --upgrade --upgrade-strategy='eager'         'setuptools'         'pip'         'wheel'     && python3 -m pip install --no-cache-dir --upgrade --upgrade-strategy='eager'         'Django[argon2]==3.1.7'         'Pillow==7.2.0'         'django_bleach==0.6.1'         'django-ckeditor==6.0.0'         'django-cors-headers==3.5.0'         'django-dcors==0.1'         'django-debug-toolbar==3.1.1'         'django-el-pagination==3.3.0'         'django-extensions==3.0.9'         'django-simple-captcha==0.5.12'         'django-storages==1.10.1'         'django-treebeard==4.3.1'         'djangocodemirror==2.1.0'         'docutils==0.16'         'google-api-python-client==1.12.3'         'google-cloud-storage==1.31.2'         'gunicorn==20.0.4'         'psycopg2==2.8.6'         'raven==6.10.0'         'requests==2.24.0'         'simplejson==3.17.2'         'uvicorn[standard]==0.12.1'     && python3 -m pip install -e git+https://github.com/jazzband/django-flatblocks.git@master#egg=django-flatblocks     && apk del .build-deps' returned a non-zero code: 1
Finished Step #0
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
```

My Dockerfile is here: https://dpaste.org/BJC6

**Comment by martey** [comment] 2021-03-08 23:10
This is not a duplicate of #33, but should have been fixed by #36. Please reopen and comment if this is not the case.

**Closed by martey** 2021-03-08 23:10 UTC
Labels: bug

**Comment by lorddaedra** [comment] 2021-03-09 09:23
@martey, thanks for fixing. 

I see new tag and release on GitHub but no new releases on PyPi (https://pypi.org/project/django-flatblocks/#files). So what is recommended command to install package?

`python3 -m pip install --no-cache-dir --upgrade --upgrade-strategy='eager' 'https://github.com/jazzband/django-flatblocks/archive/v1.0.0.tar.gz'`?

**Comment by martey** [comment] 2021-03-09 12:46
Sorry for the delay! There was a maintenance issue that needed to be resolved before the files could be uploaded to PyPi. They are there now, so the normal command (`pip install django-flatblocks`) should work.

**Comment by lorddaedra** [comment] 2021-03-09 19:12
@martey Thank you!
